spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booklib?useSSL=false
    username: root
    password: #YOUR_PASSWORD#
  jpa:
    hibernate:
      ddl-auto: none

someParameter:
  value: 5463